name: Automatically update the novel-tcr-alleles repo

on:
  schedule:
    # Runs at 00:00 on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:
    # Allows manual running from the Actions tab

env:
  # Fix Node.js 20 deprecation warning
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install biopython receptor_utils pandas


      - name: Run script
        working-directory: scripts
        run: python3 compile-alleles.py

      - name: Commit and push if new release detected
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add releases/
          if git diff --cached --quiet; then
            echo "No new release detected, nothing to commit"
          else
            git commit -m "$(date -u '+%Y-%m-%d'): automatic update"
            git push
          fi
